# Changes here will be overwritten by Copier
_commit: bba8395
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2025'
documentation: true
email: mark@securehst.com
full_name: Mark Moreno
github_username: markm-io
has_cli: false
initial_commit: false
is_django_package: false
open_source_license: MIT
open_with_editor: false
package_name: securehst_webhook_notifier
project_name: SecureHST Webhook Notifier
project_short_description: This package helps monitor automation processes with real-time
    updates directly in various platforms.
project_slug: securehst-webhook-notifier
run_uv_sync: false
setup_github: false
setup_pre_commit: false

